name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: install sudo
        run: |
          sudo apt update
          sudo apt install -y sudo jq curl wget
      - run: sudo apt update
      - name: Build the Docker image
        run: |
          sudo apt install dos2unix -y   git
          sudo apt clean
          bash -c "find . -maxdepth 1 -type f -name \"*.sh\" -exec dos2unix {} \;"
        #   sh build.sh
      - run: mkdir -pv ./build
      - run: |
          wget -v -O masx200-docker-squash-1.2.2-image.tgz https://github.com/masx200/docker-squash-image/releases/download/Continuous-integration-b50a563d298e18a52bc36153d0ad99c5292d5606/masx200-docker-squash-1.2.2-image.tgz
          wget -v -O masx201.deno-ddns-over-https-client-deno-dns-over-https-server.1.8.2.image.tgz https://github.com/masx200/deno-ddns-over-https-client-server-image/releases/download/1.8.2/masx201.deno-ddns-over-https-client-deno-dns-over-https-server.1.8.2.image.tgz
          docker load -i masx200-docker-squash-1.2.2-image.tgz
          docker load -i masx201.deno-ddns-over-https-client-deno-dns-over-https-server.1.8.2.image.tgz
          rm -rfv masx200-docker-squash-1.2.2-image.tgz masx201.deno-ddns-over-https-client-deno-dns-over-https-server.1.8.2.image.tgz
          docker images
          docker tag crpi-dkvl22hq2vvrse0v.cn-hangzhou.personal.cr.aliyuncs.com/masx201/deno-ddns-over-https-client-deno-dns-over-https-server:1.8.2 masx200/deno-ddns-over-https-client-deno-dns-over-https-server:1.8.2

      - run: sh build.sh
      - run: docker images

        #   - name: Build and save
        #
        #     run: docker save masx200/ubuntu-maven-gradle-msopenjdk:latest | gzip > ./dist/masx200-ubuntu-maven-gradle-msopenjdk-latest-image.tgz

    #   - name: Release
    #     uses: softprops/action-gh-release@v2
    #     if: startsWith(github.ref, 'refs/heads/master')
    #     with:
    #       tag_name: Continuous-integration-${{ github.sha }}
    #       #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    #       files: |
    #         ./dist/*.tgz
